#pragma once

// 表达式引用
#include "expressions/binaryOperator.h"
#include "expressions/call.h"
#include "expressions/compare.h"
#include "expressions/constant.h"
#include "expressions/expression.h"
#include "expressions/name.h"
// 模块
#include "modules/functionDefinition.h"
#include "modules/module.h"
// 语句引用
#include "statements/assign.h"
#include "statements/break.h"
#include "statements/condition.h"
#include "statements/container.h"
#include "statements/continue.h"
#include "statements/print.h"
#include "statements/return.h"
#include "statements/statement.h"
#include "statements/while.h"
// 数据类型引用
#include "types/boolean.h"
#include "types/float.h"
#include "types/integer.h"
#include "types/null.h"
#include "types/object.h"
#include "types/string.h"
#include "types/void.h"